# Generated by Django 4.0.6 on 2022-07-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('Sport', models.CharField(choices=[('None', 'NONE'), ('Chess', 'CHESS'), ('Basket Ball', 'BASKET BALL'), ('FootBall', 'FOOTBALL'), ('Cricket', 'CRICKET'), ('Volley Ball ', 'VOLLEY BALL'), ('Floor Ball', 'FLOOR BALL'), ('Table Tennis', 'TABLE TENNIS'), ('MARTIAL ART', 'MARTIAL ART'), ('Kayaking', 'Kayaking'), (' Bobsleighing', ' Bobsleighing'), (' Canoeing', ' Canoeing'), ('Skiing', 'Skiing'), ('Surfing', 'Surfing'), ('Snorkeling', 'Snorkeling'), ('Olympic Swimming', 'Olympic Swimming')], default='None', max_length=50)),
            ],
        ),
    ]
